### ISSUE TITLE
Remove dependency on `bigint-buffer`?

### ISSUE THREAD

**Issue by MicahZoltu** [vekexasia/bigint-swissknife#1]
**Is your feature request related to a problem? Please describe.**
Remove the dependency on `bigint-buffer` so `bigint-uint8array` has no dependencies.

**Describe the solution you'd like**
`bigint-uint8array` has a dependency on `bigint-buffer` and it appears to be used in `native.ts`.  However, NodeJS fully supports uint8array, so there shouldn't be any need for a fallback to buffer support.  Both browser and NodeJS can just use `Uint8Array`, so there is no need for the complexity or dependencies.

**Describe alternatives you've considered**
Using another library or forking this library.

**Additional context**
`bigint-buffer` brings in several transitive dependencies, so removing it as a dependency would also remove those.

**Comment by vekexasia** [comment]
hey @MicahZoltu the dependency currently is there cause of performance reasons.


Currently the "browser" conversion is 3x slower than the bigint-buffer NAPI integration. 
```
✓ newArray (2)
  · native   4,239,630.32 ops/sec ±0.69% (2119816 samples) fastest
  · browser  1,103,549.21 ops/sec ±0.37% ( 551775 samples)
✓ reuseArray (2) 
  · native   3,395,706.54 ops/sec ±0.40% (1697854 samples) fastest
  · browser  1,113,350.88 ops/sec ±0.31% ( 556676 samples)
```

I initially started working on a rust reimplementation of bigint-buffer which could also work in browser env via webasm so that i could remove the dependency alltogether. 

I am not sure though if i will be able to have  working version in the near future.

**Comment by MicahZoltu** [comment]
Could the native version be extracted to a peer dependency so people who don't care about the performance difference can have a smaller supply chain attack surface area and simpler dependency hierarchy, while those who have some need for extreme performance in bigint/buffer conversions can add the peer dependency?

**Comment by vekexasia** [comment]
I think that is a good idea tbh. Would you like to contribute or prefer me to do it?

**Comment by MicahZoltu** [comment]
Looks great, thanks!  I left one minor comment on the PR, but it definitely isn't a big issue.
